### ISSUE TITLE
Incorrect to hit calculation

### ISSUE THREAD

**Issue by daeuiot** [missing-q/emblem20#2]
https://github.com/missing-q/emblem20/blob/a93e60d1e7d80043ad2289d850393a2e127467be/Basic%20Package/sheet.html#L3927
To hit is meant to be (skill*3+luck)/2+wHit (or skill*1.5+luck*.5+wHit)

**Comment by missing-q** [comment]
I'm using the hit formula from Xeohelios' Fire Emblem TTRPG, which is (Skill x 3) + wHit + (Luck / 2) + any additional modifiers.
