### ISSUE TITLE
Detecting magic weapons doesn't work

### ISSUE THREAD

**Issue by kizo-also-known-as-kizuna** [missing-q/emblem20#5]
if ( (PhysWepTypes.includes(WTypeB))||(PhysWeps.includes(WNameB)) ){
            DmgtypeB = "Physical";
            DmgB = (StrB + MtB) - DefA;
        } else if ( (MWepTypes.includes(WTypeB))||(MagWeps.includes(WNameB)) ){
            DmgtypeB = "Magical";
            DmgB = (MagB + MtB) - ResA;

as an example for the code above, If you had a flame shuriken, it would first check that it is a shuriken and make it a physical weapon then it would skip over checking that it name is "Flame Shuriken" because the first if statement was true.

**Comment by kizo-also-known-as-kizuna** [comment]
The way I fixed it was by deleting the else in the else if, seemed to work fine for me.
EDIT Do not do that it does not fix it

**Comment by kizo-also-known-as-kizuna** [comment]
I change the above code to this
if ( ((PhysWepTypes.includes(WTypeB))||(PhysWeps.includes(WNameB))) && (!MagWeps.includes(WNameA)) ){
            DmgtypeB = "Physical";
            DmgB = (StrB + MtB) - DefA;
        }
        else if ( (MWepTypes.includes(WTypeB))||(MagWeps.includes(WNameB)) ){
            DmgtypeB = "Magical";
            DmgB = (MagB + MtB) - ResA;
        }
And it seems to work

**Comment by missing-q** [comment]
Thank you! The bug has been fixed, and the newest release should be out by Tuesday. Thanks for your patience!
