### ISSUE TITLE
Level up doesn't level Res even when it's at 100% chance

### ISSUE THREAD

**Issue by kizo-also-known-as-kizuna** [missing-q/emblem20#6]
I was doing some testing and I realized that when a character would level up he would never get a point in res even at 100%. I tested it with other attributes but the rest of them works as intended.

**Comment by missing-q** [comment]
Was this in a normal combat situation, or were you using a staff or something else that might give the character EXP as well?

**Comment by kizo-also-known-as-kizuna** [comment]
I tried with both staff and regular combat but both will not give Res.

**Comment by missing-q** [comment]
Thank you! The bug has been fixed, and the newest release should be out by Tuesday. Thanks for your patience!
